name: 'Terraform AWS Infrastructure Deployment'

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: 'Terraform AWS Deploy'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:

    - name: 📦 Checkout Repository
      uses: actions/checkout@v4

    - name: ⚙️ Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: 🔐 Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: 🧪 Terraform Init
      run: terraform init

    - name: 🔍 Terraform Plan
      run: terraform plan

    - name: 🚀 Terraform Apply
      run: terraform apply -auto-approve

    # ---------------------------------------------
    # 🧹 OPTIONAL: Terraform Destroy Step (Disabled)
    # ---------------------------------------------
    # - name: 💣 Terraform Destroy
    #   run: terraform destroy -auto-approve
